### ISSUE TITLE
Need to remove relative permalinks in _config.yml

### ISSUE THREAD

**Issue by nateGeorge** [trevordmiller/github-pages-starter-kit#1]
Nice looking starter! But when I used the repo as a starter it gave me an error saying I need to remove relative_permalinks in the _config.yml.  Also, I didn't finish building everything (maybe that's why) but my version wasn't looking like your demo.

**Comment by trevordmiller** [comment]
Sorry I don't maintain this repo anymore. I've updated the description with a `[DEPRECATED]` note. Feel free to fork it :)
